image: gitpod/workspace-full
tasks:
  - init: |
      python -m venv .venv
      source .venv/bin/activate
      pip install -r requirements.txt
    command: python app.py
ports:
  - port: 5000
    onOpen: open-browser