runtime: python39
service: default
instance_class: F2  # Minimum for Vertex AI integration

env_variables:
  GCP_PROJECT: your-project-id  # Non-sensitive
  DB_NAME: eco_footprint        # Non-sensitive
  COLLECTION_NAME: mealdb_recipes
  BUCKET_NAME: recipe-audio-bucket
  GCP_REGION: us-central1
  FLASK_ENV: production
entrypoint: gunicorn -c gunicorn.conf.py app:app

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 3
  target_cpu_utilization: 0.6